version: "3.8"

services:
    db:
        container_name: mongo_compose
        image: mongo
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        volumes: 
            - db-data:/var/lib/mongodb/data
        ports: 
            - "27017:27017"
        networks:
            - custom


    express:
        container_name: mexpress_compose
        image: mongo-express
        environment: 
            - ME_CONFIG_MONGODB_SERVER=db
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=testing
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_BASICAUTH_USERNAME=DASistemas
            - ME_CONFIG_BASICAUTH_PASSWORD=ex-especial567
        ports:
            - "8081:8081"
        networks:
            - custom
        depends_on: 
            - db
    
    goperson:
        container_name: persondb
        build:
            context: .
            dockerfile: gomongo/build/production.Dockerfile
        restart: "no"
        depends_on: 
            - db
        networks: 
            - custom
        environment: 
            - MONGO_URL=db
            - MONGO_USR=root
            - MONGO_PWD=example
            - MONGO_PORT=27017
        ports: 
            - "80:8080"

    goapi:
        container_name: personapi
        build:
            context: .
            dockerfile: goapi/build/production.Dockerfile
        restart: always
        depends_on: 
            - db
        networks: 
            - custom
        environment: 
            - MONGO_URL=db
            - MONGO_USR=root
            - MONGO_PWD=example
            - MONGO_PORT=27017
        ports: 
            - "7777:7777"
        
volumes: 
    db-data:

networks:
    custom:
        driver: bridge
